import { Department } from './department.model';

export const Departments: Department[] = [
    new Department(1,"org01", 0,"CEO", "Highest Level"),
    new Department(2,"org01", 1,"CFO", "Second Level"),
    new Department(3,"org01", 1,"CMO", "Second Level"),
    new Department(4,"org01", 1,"CTO", "Second Level"),
    new Department(5,"org01", 2,"Financial", "Third Level"),
    new Department(6,"org01", 2,"Auditors","Third Level"),
    new Department(7,"org01", 3,"X","Third Level"),
    new Department(8,"org01", 3, "Y","Third Level"),
    new Department(9,"org01", 4, "Z","Third Level"),
    new Department(1,"org02", 0,"CEO", "Highest Level"),
    new Department(2,"org02", 1,"CFO", "Second Level"),
    new Department(3,"org02", 1,"CMO", "Second Level"),
    new Department(4,"org02", 1,"CTO", "Second Level"),
    new Department(5,"org02", 2,"Financial", "Third Level"),
    new Department(6,"org02", 2,"Auditors","Third Level"),
    new Department(7,"org02", 3,"X","Third Level"),
    new Department(8,"org02", 3, "Y","Third Level"),
    new Department(9,"org02", 4, "Z","Third Level"),
    new Department(1,"org03", 0,"CEO", "Highest Level"),
    new Department(2,"org03", 1,"CFO", "Second Level"),
    new Department(3,"org03", 1,"CMO", "Second Level"),
    new Department(4,"org03", 1,"CTO", "Second Level"),
    new Department(5,"org03", 2,"Financial", "Third Level"),
    new Department(6,"org03", 2,"Auditors","Third Level"),
    new Department(7,"org03", 3,"X","Third Level"),
    new Department(8,"org03", 3, "Y","Third Level"),
    new Department(9,"org03", 4, "Z","Third Level")
]
